CREATE TABLE friend (
	friend_no INT AUTO_INCREMENT PRIMARY KEY,
    user_id VARCHAR(16) NOT NULL,
	friend_id VARCHAR(16) NOT NULL,
    FOREIGN KEY (user_id) REFERENCES Members(user_id) ON DELETE CASCADE,
    FOREIGN KEY (friend_id) REFERENCES Members(user_id) ON DELETE CASCADE
);